### ISSUE TITLE
No tick improvement seen

### ISSUE THREAD

**Issue by phife-dawg** [jonathangarelick/tick-fixer#2] opened 2024-01-10 01:45 UTC
Hi @jonathangarelick @cube-god unfortunately this does not seem to make the same improvements as running the command from the reddit post:

ping route get default | grep gateway | awk '{print $2}' -i 0.2

I am monitoring tick health using https://runelite.net/plugin-hub/show/ticktracker.

When I enable this new tick fixer plugin my tick health does not change, it remains around 60%. When I run the aforementioned command, it immediately increases to >99%.

I would love to provide more detail on this, but I am not sure how to capture any data. Please let me know what other info I can provide!

I am using a 2022 Macbook Air M2

**Comment by jonathangarelick** [comment] 2024-01-10 02:52
Just to be sure -- you are turning on the tick fixer before you log in, right? If you've been playing a long time and turn it on, then it will probably take a long time for the average to rise.

**Comment by phife-dawg** [comment] 2024-01-10 03:46
Thanks, please let me know if I can help at all!

**Comment by jonathangarelick** [comment] 2024-01-10 17:16
Could you please paste the output of the following command?

`cat ~/.runelite/logs/client.log | grep TickFixerPlugin`

**Comment by phife-dawg** [comment] 2024-01-10 18:26
2024-01-10 10:09:37 PST [AWT-EventQueue-0] INFO  com.jonathang.TickFixerPlugin - Tick Fixer for Mac started.
2024-01-10 10:09:39 PST [pool-9-thread-1] ERROR com.jonathang.TickFixerPlugin - Failed to ping default gateway 10 times. Terminating.
[REDACTED]:~ [REDACTED]$

**Comment by jonathangarelick** [comment] 2024-01-10 21:31
Thanks. Could you tell me what this outputs, if anything?

`netstat -nr | awk '/default/ {print $2}' | head -n1`

**Comment by phife-dawg** [comment] 2024-01-10 22:44
It spits out my router ip address: 192.168.86.1

**Comment by jonathangarelick** [comment] 2024-01-11 01:11
Thank you. I have added improved logging and will submit an update request shortly. Hopefully, that will help us get to the bottom of this.

**Comment by jonathangarelick** [comment] 2024-02-03 17:36
(This is more of a personal note for me)

Looks like the problem is with Java's `isReachable` method. It seems to be [unreliable](https://stackoverflow.com/questions/9922543/why-does-inetaddress-isreachable-return-false-when-i-can-ping-the-ip-address). I will try to implement one of the workarounds.

**Comment by jonathangarelick** [comment] 2024-03-17 21:23
Hi @phife-dawg ,

I just tested out the current version of Tick Fixer for 30 minutes, and the percentage stayed consistently above 90. Could you please try running it again? Also, make sure the plugin is enabled before you log in.

If you are still experiencing the issue, please run the command `cat ~/.runelite/logs/client.log | grep TickFixerPlugin` one more time. The logging that I added should give more clarity on what the root cause is.

**Comment by phife-dawg** [comment] 2024-03-17 22:45
Hey @jonathangarelick 

`2024-03-17 15:42:52 PDT [AWT-EventQueue-0] INFO  com.jonathang.TickFixerPlugin - Tick Fixer for Mac started.
2024-03-17 15:42:55 PDT [pool-9-thread-1] ERROR com.jonathang.TickFixerPlugin - Failed to ping default gateway 10 times. Terminating.`

**Comment by jonathangarelick** [comment] 2024-03-22 02:54
Thank you. I have updated the plugin.

If you could please do the following:
- Close RuneLite (to get the latest version of the plugin)
- Enable debug mode for RuneLite. You can do this by running `/Applications/RuneLite.app/Contents/MacOS/RuneLite --configure`, and clicking the checkbox next to "Debug" then click Save. [More info](https://github.com/runelite/runelite/wiki/RuneLite-Launcher-Configuration)
- Start RuneLite and test the plugin again

I have a hunch that it is a permissions problem on your computer. Is it owned by your school or company? Also, is your Mac user [an administrator](https://oit.ncsu.edu/it-security/antivirus/how-to-tell-if-you-are-an-administrator/#osx)?

If the plugin still does not work, please paste the logs again. Thanks!

**Comment by jonathangarelick** [comment] 2024-04-08 17:09
Hi @phife-dawg ,

Just wanted to see if my changes resolved your issue.

Thanks :-)

**Comment by jonathangarelick** [comment] 2024-04-24 18:20
Closing due to inactivity.

**Comment by Intecpsp** [comment] 2024-04-27 02:32
This is an issue on my personal Mac as well, I can confirm I am an administrator on it

**Comment by jonathangarelick** [comment] 2024-04-27 16:03
> This is an issue on my personal Mac as well, I can confirm I am an administrator on it

Hi, thanks for the report. Unfortunately, this is quite a pesky bug. Would you be willing to hop on a short video call so I can see what's going on?

My Discord username is jonathang0493, and my email is firstname @ lastname dot net. Thanks! :-)

**Comment by jonathangarelick** [comment] 2024-04-29 22:57
After getting on a call with @phife-dawg , it appears that the issue is *not* finding the default gateway. For some reason the requests are failing. He is using a computer he owns and he is the administrator.

The plot thickens...

**Comment by jonathangarelick** [comment] 2024-05-01 21:34
Hi @phife-dawg , @Intecpsp . I have just worked on a significant improvement to the reliability of the tick fixer. Hopefully it will sort this issue out. You can follow the status of the update here: 

https://github.com/runelite/plugin-hub/pull/5954

**Comment by jonathangarelick** [comment] 2024-05-18 16:24
@phife-dawg @Intecpsp 

The new version is available now. I tested it on my computer and it seems to be a big improvement! Please try it out and let me know if it works for you.

**Comment by Intecpsp** [comment] 2024-05-18 17:51
I saw the update come through and have had MUCH better numbers with this update, wifi is useable! Thank you!

**Comment by jonathangarelick** [comment] 2024-06-22 15:35
Closing this as everything appears to be resolved.  @phife-dawg if you are still having issues, please let me know. Thanks!

**Closed by jonathangarelick** 2024-06-22 15:35 UTC
